Java: web/javascript.js
Page: web/index.html
Styles: web/style.css
captureDirectory: sampleImages
captureRate: 24
captureStillOn: true
emailPort: 587
extractionDirectory: extraction/
extractionThreshold: 1000
inferIdentity: True
notDelay: 300
notificationAuth: NotifyMe1!
notificationType: 0
ownerEmail: notify.lockindustries@gmail.com
storageDirectory: storage/
senderEmail: notify.lockindustries@gmail.com
smtpServer: smtp.gmail.com
frameRate: 24
resolution: 240x240
rotation: 180
turingCoreTFLITE: 'AI/lockIndust001FactialRecognitionb3TFlite'
idCoreTFLITE: 'AI/lockIndust001FactialRecognitionb3TFlite'
boltControl: False
boltDelay: 5
networkAddress: 10.0.0.30
networkPort: 7777
turingThres: 0.95
idThres: 0.95